import { Dimensions, StyleSheet } from "react-native";

const { height: SH } = Dimensions.get("window");
export const SHEET_H = SH * 0.82;

export const st = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#0A0A0A", padding: 20 },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginTop: 10,
    marginBottom: 16,
  },
  headerLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: "#555",
    letterSpacing: 3,
  },
  headerBrand: {
    fontSize: 18,
    fontWeight: "900",
    color: "#D4AF37",
    letterSpacing: 2,
    marginTop: 2,
  },
  headerUser: { color: "#666", fontSize: 13, marginTop: 6 },
  headerBtn: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: "#D4AF37",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer" as any,
  },
  headerBtnNotif: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: "#141414",
    borderWidth: 1,
    borderColor: "#1E1E1E",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer" as any,
  },
  headerBadge: {
    position: "absolute" as any,
    top: -4,
    right: -4,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: "#D4AF37",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  headerBadgeText: { color: "#0A0A0A", fontSize: 10, fontWeight: "900" },
  headerBtnOut: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#222",
    cursor: "pointer" as any,
  },
  sedeRow: { flexDirection: "row", gap: 8, marginBottom: 16 },
  sedeTab: {
    flex: 1,
    padding: 12,
    borderRadius: 14,
    backgroundColor: "#141414",
    borderWidth: 1,
    borderColor: "#1E1E1E",
    alignItems: "center",
    cursor: "pointer" as any,
  },
  sedeTabA: {
    borderColor: "#D4AF37",
    backgroundColor: "rgba(212,175,55,0.08)",
  },
  sedeTabText: { color: "#555", fontWeight: "700", fontSize: 14 },
  sedeTabTextA: { color: "#D4AF37" },
  statRow: { flexDirection: "row", marginBottom: 8 },
  statCard: {
    flex: 1,
    backgroundColor: "#141414",
    borderRadius: 14,
    padding: 16,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#1E1E1E",
  },
  statVal: { fontSize: 28, fontWeight: "900", color: "#D4AF37" },
  statLbl: {
    fontSize: 11,
    color: "#555",
    fontWeight: "600",
    marginTop: 2,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  secTitle: {
    fontSize: 11,
    fontWeight: "700",
    color: "#555",
    letterSpacing: 3,
    textTransform: "uppercase",
    marginBottom: 12,
    marginTop: 20,
  },
  dataBtn: {
    backgroundColor: "#141414",
    borderRadius: 14,
    padding: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#1E1E1E",
    cursor: "pointer" as any,
  },
  dataBtnText: { color: "#FFF", fontSize: 16, fontWeight: "700" },
  dataRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 4,
  },
  dataArrow: {
    width: 44,
    height: 50,
    borderRadius: 14,
    backgroundColor: "#141414",
    borderWidth: 1,
    borderColor: "#1E1E1E",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer" as any,
  },
  dataArrowText: { color: "#D4AF37", fontSize: 22, fontWeight: "300" },
  dataCenterBtn: {
    flex: 1,
    backgroundColor: "#141414",
    borderRadius: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "#1E1E1E",
    alignItems: "center",
    cursor: "pointer" as any,
  },
  dataCenterText: { color: "#FFF", fontSize: 15, fontWeight: "700" },
  calBox: {
    backgroundColor: "#141414",
    borderRadius: 14,
    overflow: "hidden",
    marginTop: 8,
    borderWidth: 1,
    borderColor: "#1E1E1E",
  },
  filtriWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 12,
  },
  chip: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: "#141414",
    borderWidth: 1,
    borderColor: "#1E1E1E",
    cursor: "pointer" as any,
  },
  chipA: { borderColor: "#D4AF37", backgroundColor: "rgba(212,175,55,0.08)" },
  chipText: { color: "#555", fontSize: 13, fontWeight: "600" },
  chipTextA: { color: "#D4AF37" },
  filtriDrop: {
    backgroundColor: "#141414",
    borderRadius: 14,
    marginTop: 8,
    borderWidth: 1,
    borderColor: "#1E1E1E",
    overflow: "hidden",
  },
  filtroItem: { padding: 14, cursor: "pointer" as any },
  filtroItemA: { backgroundColor: "rgba(212,175,55,0.06)" },
  filtroItemText: { color: "#888", fontSize: 14, fontWeight: "600" },
  filtroItemTextA: { color: "#D4AF37" },
  actRow: { flexDirection: "row", gap: 10, marginBottom: 14, marginTop: 6 },
  actRow2: { flexDirection: "row", marginBottom: 14 },
  actGold: {
    flex: 2,
    padding: 14,
    borderRadius: 12,
    backgroundColor: "#D4AF37",
    alignItems: "center",
    cursor: "pointer" as any,
  },
  actGoldText: { color: "#0A0A0A", fontWeight: "800", fontSize: 14 },
  actRed: {
    flex: 1,
    padding: 14,
    borderRadius: 12,
    backgroundColor: "rgba(244,67,54,0.06)",
    borderWidth: 1,
    borderColor: "rgba(244,67,54,0.2)",
    alignItems: "center",
    cursor: "pointer" as any,
  },
  actRedText: { color: "#F44336", fontWeight: "700", fontSize: 13 },
  actOrange: {
    flex: 1,
    padding: 14,
    borderRadius: 12,
    backgroundColor: "rgba(229,115,74,0.06)",
    borderWidth: 1,
    borderColor: "rgba(229,115,74,0.25)",
    alignItems: "center",
    cursor: "pointer" as any,
  },
  actOrangeText: { color: "#E5734A", fontWeight: "700", fontSize: 13 },
  oreBtn: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: "#141414",
    borderWidth: 1,
    borderColor: "#2A2A2A",
    cursor: "pointer" as any,
  },
  oreBtnA: { backgroundColor: "rgba(229,115,74,0.12)", borderColor: "#E5734A" },
  oreBtnText: { color: "#666", fontWeight: "700", fontSize: 15 },
  oreBtnTextA: { color: "#E5734A" },
  absCard: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "rgba(244,67,54,0.04)",
    borderRadius: 12,
    padding: 14,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "rgba(244,67,54,0.15)",
  },
  absText: { color: "#F44336", fontSize: 14, fontWeight: "600" },
  absBtn: {
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 8,
    backgroundColor: "rgba(76,175,80,0.08)",
    borderWidth: 1,
    borderColor: "rgba(76,175,80,0.2)",
    cursor: "pointer" as any,
  },
  absBtnText: { color: "#4CAF50", fontSize: 12, fontWeight: "700" },
  emptyBox: { alignItems: "center", padding: 40 },
  emptyText: { color: "#444", fontSize: 16 },
  colCont: { flexDirection: "row", gap: 12, paddingBottom: 10 },
  col: {
    width: 200,
    backgroundColor: "#141414",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#1E1E1E",
    overflow: "hidden",
  },
  colHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 14,
    backgroundColor: "rgba(212,175,55,0.05)",
    borderBottomWidth: 1,
    borderBottomColor: "#1E1E1E",
  },
  colHeadText: { color: "#D4AF37", fontSize: 14, fontWeight: "700" },
  colNum: {
    color: "#555",
    fontSize: 12,
    fontWeight: "700",
    backgroundColor: "#0A0A0A",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
  },
  colNone: { color: "#333", fontSize: 13, padding: 14, textAlign: "center" },
  colItem: { padding: 12, borderBottomWidth: 1, borderBottomColor: "#1E1E1E" },
  colOra: {
    color: "#D4AF37",
    fontSize: 16,
    fontWeight: "800",
    marginBottom: 4,
  },
  colCli: { color: "#FFF", fontSize: 14, fontWeight: "600", marginBottom: 4 },
  colServ: { color: "#666", fontSize: 12, marginBottom: 8 },
  colDel: {
    alignSelf: "flex-end",
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 6,
    backgroundColor: "rgba(244,67,54,0.06)",
    borderWidth: 1,
    borderColor: "rgba(244,67,54,0.2)",
    cursor: "pointer" as any,
  },
  colDelText: { color: "#F44336", fontSize: 11, fontWeight: "700" },
  tblHeaderRow: {
    flexDirection: "row",
    borderBottomWidth: 2,
    borderBottomColor: "#1E1E1E",
    paddingBottom: 10,
    marginBottom: 4,
  },
  tblOraCol: { width: 60, justifyContent: "center", alignItems: "center" },
  tblOraHeader: {
    color: "#555",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1,
  },
  tblBarbCol: {
    width: 140,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  tblBarbName: { color: "#D4AF37", fontSize: 13, fontWeight: "700" },
  tblRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#1A1A1A",
    minHeight: 70,
    zIndex: 1,
  },
  tblRowOccupata: { backgroundColor: "rgba(212,175,55,0.02)" },
  tblOraText: { color: "#D4AF37", fontSize: 14, fontWeight: "800" },
  tblCell: {
    width: 140,
    paddingHorizontal: 4,
    paddingVertical: 6,
    justifyContent: "center",
    overflow: "visible" as any,
    zIndex: 1,
  },
  tblAppCard: {
    backgroundColor: "#1A1A1A",
    borderRadius: 10,
    padding: 8,
    borderLeftWidth: 3,
    borderLeftColor: "#D4AF37",
    position: "relative" as any,
  },
  tblAppCliente: {
    color: "#FFF",
    fontSize: 13,
    fontWeight: "700",
    marginBottom: 2,
  },
  tblAppServizio: { color: "#888", fontSize: 11 },
  tblAppDurata: { color: "#555", fontSize: 10, marginTop: 2 },
  tblAppDel: {
    position: "absolute",
    top: 4,
    right: 4,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "rgba(244,67,54,0.1)",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer" as any,
  },
  tblAppDelText: { color: "#F44336", fontSize: 10, fontWeight: "700" },
  tblEmpty: { alignItems: "center", justifyContent: "center", height: 50 },
  tblEmptyText: { color: "#222", fontSize: 16 },
  tblBlockedCell: {
    backgroundColor: "rgba(212,175,55,0.04)",
    borderRadius: 8,
    padding: 6,
    borderLeftWidth: 3,
    borderLeftColor: "rgba(212,175,55,0.2)",
    justifyContent: "center",
    height: 50,
  },
  tblBlockedText: {
    color: "#444",
    fontSize: 10,
    fontStyle: "italic",
    textAlign: "center",
  },
  singleRow: {
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#1A1A1A",
    minHeight: 60,
    paddingVertical: 6,
  },
  singleRowOcc: { backgroundColor: "rgba(212,175,55,0.02)" },
  singleOraBox: { width: 60, alignItems: "center", justifyContent: "center" },
  singleOra: { color: "#D4AF37", fontSize: 14, fontWeight: "800" },
  singleApp: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1A1A1A",
    borderRadius: 12,
    padding: 12,
    marginLeft: 8,
    borderLeftWidth: 3,
    borderLeftColor: "#D4AF37",
  },
  singleCliente: {
    color: "#FFF",
    fontSize: 15,
    fontWeight: "700",
    marginBottom: 2,
  },
  singleServizio: { color: "#888", fontSize: 12 },
  singleBtns: { flexDirection: "row", gap: 8, marginLeft: 10 },
  singleEditBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "rgba(212,175,55,0.08)",
    borderWidth: 1,
    borderColor: "rgba(212,175,55,0.2)",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer" as any,
  },
  singleEditText: { fontSize: 14 },
  singleDelBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "rgba(244,67,54,0.06)",
    borderWidth: 1,
    borderColor: "rgba(244,67,54,0.2)",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer" as any,
  },
  singleDelText: { fontSize: 14 },
  singleEmpty: { flex: 1, marginLeft: 8, paddingVertical: 8 },
  singleEmptyText: { color: "#222", fontSize: 13 },
  singleRowBlocked: {
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#1A1A1A",
    minHeight: 44,
    paddingVertical: 2,
  },
  singleBlockedBar: {
    flex: 1,
    marginLeft: 8,
    backgroundColor: "rgba(212,175,55,0.04)",
    borderRadius: 8,
    padding: 8,
    borderLeftWidth: 3,
    borderLeftColor: "rgba(212,175,55,0.2)",
  },
  singleBlockedText: { color: "#444", fontSize: 12, fontStyle: "italic" },
  listCont: { gap: 8 },
  listCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#141414",
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: "#1E1E1E",
    gap: 12,
  },
  listOraBox: {
    width: 56,
    height: 56,
    borderRadius: 14,
    backgroundColor: "rgba(212,175,55,0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  listOra: { color: "#D4AF37", fontSize: 16, fontWeight: "800" },
  listCli: { color: "#FFF", fontSize: 15, fontWeight: "700", marginBottom: 3 },
  listInfo: { color: "#666", fontSize: 12 },
  listDel: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: "rgba(244,67,54,0.06)",
    borderWidth: 1,
    borderColor: "rgba(244,67,54,0.2)",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer" as any,
  },
  listDelText: { color: "#F44336", fontSize: 14, fontWeight: "700" },
  modalOv: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.75)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    zIndex: 100,
  },
  modal: {
    backgroundColor: "#111",
    borderRadius: 24,
    padding: 24,
    width: "100%",
    maxWidth: 440,
    maxHeight: "90%",
    borderWidth: 1,
    borderColor: "#1A1A1A",
  },
  mTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: "#D4AF37",
    marginBottom: 4,
  },
  mDate: { color: "#666", fontSize: 13, marginBottom: 20 },
  mLabel: {
    color: "#555",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 2,
    marginBottom: 8,
    marginTop: 16,
    textTransform: "uppercase",
  },
  mInput: {
    backgroundColor: "#0A0A0A",
    borderWidth: 1,
    borderColor: "#1A1A1A",
    borderRadius: 12,
    padding: 14,
    color: "#FFF",
    fontSize: 15,
  },
  mGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  mChip: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: "#0A0A0A",
    borderWidth: 1,
    borderColor: "#1A1A1A",
    cursor: "pointer" as any,
  },
  mChipA: { borderColor: "#D4AF37", backgroundColor: "rgba(212,175,55,0.08)" },
  mChipText: { color: "#555", fontSize: 13, fontWeight: "600" },
  mChipTextA: { color: "#D4AF37" },
  mNoSlot: {
    color: "#444",
    fontSize: 14,
    textAlign: "center",
    marginVertical: 16,
  },
  oGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  oBtn: {
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 12,
    backgroundColor: "#0A0A0A",
    borderWidth: 1,
    borderColor: "#1A1A1A",
    cursor: "pointer" as any,
  },
  oBtnA: { borderColor: "#D4AF37", backgroundColor: "rgba(212,175,55,0.1)" },
  oText: { color: "#555", fontSize: 15, fontWeight: "700" },
  oTextA: { color: "#D4AF37" },
  mBtns: { flexDirection: "row", gap: 10, marginTop: 24 },
  mCancel: {
    flex: 1,
    padding: 15,
    borderRadius: 12,
    backgroundColor: "#1A1A1A",
    alignItems: "center",
    cursor: "pointer" as any,
  },
  mConfirm: {
    flex: 1,
    padding: 15,
    borderRadius: 12,
    backgroundColor: "#D4AF37",
    alignItems: "center",
    cursor: "pointer" as any,
  },
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.6)",
    zIndex: 50,
  },
  sheet: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#111",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    zIndex: 60,
    paddingHorizontal: 24,
    borderTopWidth: 1,
    borderTopColor: "#1E1E1E",
  },
  handle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#333",
    alignSelf: "center",
    marginTop: 12,
    marginBottom: 20,
  },
  sHead: { alignItems: "center", marginBottom: 24 },
  sAvatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "rgba(212,175,55,0.12)",
    borderWidth: 2,
    borderColor: "#D4AF37",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  sAvatarText: { color: "#D4AF37", fontSize: 28, fontWeight: "800" },
  sName: { color: "#FFF", fontSize: 20, fontWeight: "800" },
  sEmail: { color: "#555", fontSize: 13, marginTop: 4 },
  sActions: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 20,
    marginBottom: 24,
  },
  sActBtn: { alignItems: "center", gap: 6, cursor: "pointer" as any },
  sActIcon: {
    width: 52,
    height: 52,
    borderRadius: 16,
    backgroundColor: "#1A1A1A",
    borderWidth: 1,
    borderColor: "#222",
    alignItems: "center",
    justifyContent: "center",
  },
  sActText: { color: "#888", fontSize: 12, fontWeight: "600" },
  sSec: {
    backgroundColor: "#0A0A0A",
    borderRadius: 18,
    padding: 18,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#1A1A1A",
  },
  sSecLabel: {
    color: "#D4AF37",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 2,
    marginBottom: 12,
  },
  sInput: {
    backgroundColor: "#141414",
    borderWidth: 1,
    borderColor: "#1E1E1E",
    borderRadius: 12,
    padding: 13,
    color: "#FFF",
    fontSize: 15,
  },
  sBtnRow: { flexDirection: "row", gap: 10, marginTop: 14 },
  sBtnCancel: {
    flex: 1,
    padding: 13,
    borderRadius: 12,
    backgroundColor: "#1A1A1A",
    alignItems: "center",
    cursor: "pointer" as any,
  },
  sBtnSave: {
    flex: 1,
    padding: 13,
    borderRadius: 12,
    backgroundColor: "#D4AF37",
    alignItems: "center",
    cursor: "pointer" as any,
  },

  // Bottom tab bar
  bottomBar: {
    flexDirection: "row",
    backgroundColor: "#111",
    borderTopWidth: 1,
    borderTopColor: "#1A1A1A",
    paddingBottom: 10,
    paddingTop: 6,
  },
  bottomTab: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    gap: 3,
    cursor: "pointer" as any,
  },
  bottomTabLabel: {
    color: "#444",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  bottomTabLabelA: { color: "#D4AF37" },

  // Week navigation
  weekHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    gap: 8,
  },
  weekArrow: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "#141414",
    borderWidth: 1,
    borderColor: "#1E1E1E",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer" as any,
  },
  weekMonthLabel: {
    flex: 1,
    color: "#FFF",
    fontSize: 15,
    fontWeight: "700",
    textAlign: "center",
  },
  weekDaysRow: { flexDirection: "row", gap: 4, marginBottom: 8 },
  weekDayBtn: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: "#141414",
    borderWidth: 1,
    borderColor: "#1E1E1E",
    cursor: "pointer" as any,
  },
  weekDayBtnA: { backgroundColor: "#D4AF37", borderColor: "#D4AF37" },
  weekDayBtnToday: { borderColor: "rgba(212,175,55,0.5)" },
  weekDayName: {
    color: "#555",
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  weekDayNameA: { color: "#0A0A0A" },
  weekDayNum: { color: "#888", fontSize: 15, fontWeight: "800", marginTop: 1 },
  weekDayNumA: { color: "#0A0A0A" },
  weekTodayBtn: {
    alignSelf: "flex-end",
    paddingVertical: 5,
    paddingHorizontal: 14,
    borderRadius: 8,
    backgroundColor: "rgba(212,175,55,0.08)",
    borderWidth: 1,
    borderColor: "rgba(212,175,55,0.2)",
    marginBottom: 12,
    cursor: "pointer" as any,
  },
  weekTodayText: { color: "#D4AF37", fontSize: 12, fontWeight: "700" },

  // Detail modal
  detailInfo: {
    backgroundColor: "#0A0A0A",
    borderRadius: 14,
    padding: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#1A1A1A",
    gap: 14,
  },
  detailRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  detailIconBox: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: "#141414",
    alignItems: "center",
    justifyContent: "center",
  },
  detailLabel: {
    color: "#555",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  detailValue: { color: "#FFF", fontSize: 15, fontWeight: "700", marginTop: 1 },
  detailBtns: { flexDirection: "row", gap: 10, marginBottom: 10 },
  detailEditBtn: {
    flex: 1,
    padding: 14,
    borderRadius: 12,
    backgroundColor: "rgba(212,175,55,0.08)",
    borderWidth: 1,
    borderColor: "rgba(212,175,55,0.25)",
    alignItems: "center",
    cursor: "pointer" as any,
  },
  detailEditText: { color: "#D4AF37", fontWeight: "700", fontSize: 14 },
  detailDelBtn: {
    flex: 1,
    padding: 14,
    borderRadius: 12,
    backgroundColor: "rgba(244,67,54,0.06)",
    borderWidth: 1,
    borderColor: "rgba(244,67,54,0.2)",
    alignItems: "center",
    cursor: "pointer" as any,
  },
  detailDelText: { color: "#F44336", fontWeight: "700", fontSize: 14 },
});
