import { StyleSheet } from "react-native";

export const st = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#0A0A0A", padding: 24 },
  header: { marginTop: 20, marginBottom: 20 },
  backBtn: { marginBottom: 20, cursor: "pointer" as any },
  backText: { color: "#D4AF37", fontSize: 14, fontWeight: "600" },
  title: { fontSize: 28, fontWeight: "800", color: "#FFF" },
  confirmBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "rgba(76,175,80,0.08)",
    borderWidth: 1,
    borderColor: "rgba(76,175,80,0.2)",
    borderRadius: 14,
    padding: 14,
    marginBottom: 16,
  },
  confirmText: { color: "#4CAF50", fontSize: 14, fontWeight: "700" },
  card: {
    backgroundColor: "#141414",
    borderRadius: 18,
    padding: 18,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "#1E1E1E",
  },
  cardRow: { flexDirection: "row", alignItems: "center", marginBottom: 14 },
  dateBox: {
    width: 60,
    height: 70,
    borderRadius: 14,
    backgroundColor: "rgba(212,175,55,0.08)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  dateDay: { color: "#D4AF37", fontSize: 11, fontWeight: "600" },
  dateNum: { color: "#FFF", fontSize: 24, fontWeight: "800" },
  dateMon: { color: "#666", fontSize: 11, fontWeight: "600" },
  cardServ: { color: "#FFF", fontSize: 17, fontWeight: "700", marginBottom: 6 },
  cardDet: { color: "#666", fontSize: 13, marginBottom: 4 },
  sedeTag: { color: "#D4AF37", fontSize: 11, fontWeight: "600" },
  cardPrice: { color: "#D4AF37", fontSize: 22, fontWeight: "800" },
  cardFoot: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: "#1E1E1E",
    paddingTop: 12,
  },
  statoChip: {
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: "rgba(76,175,80,0.1)",
  },
  statoText: { fontSize: 12, fontWeight: "700", color: "#4CAF50" },
  cancelBtn: {
    paddingVertical: 8,
    paddingHorizontal: 18,
    borderRadius: 10,
    backgroundColor: "rgba(244,67,54,0.08)",
    borderWidth: 1,
    borderColor: "rgba(244,67,54,0.3)",
    cursor: "pointer" as any,
  },
  cancelText: { color: "#F44336", fontWeight: "700", fontSize: 13 },
  emptyBox: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 60,
  },
  emptyTitle: {
    color: "#555",
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 6,
  },
  emptySub: { color: "#444", fontSize: 14, marginBottom: 24 },
  ctaBtn: {
    backgroundColor: "#D4AF37",
    paddingVertical: 14,
    paddingHorizontal: 40,
    borderRadius: 12,
    cursor: "pointer" as any,
  },
  ctaText: { color: "#0A0A0A", fontSize: 16, fontWeight: "800" },
});
