import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#0A0A0A", padding: 24 },
  header: { marginTop: 20, marginBottom: 10 },
  backButton: { marginBottom: 20, cursor: "pointer" as any },
  backButtonText: { color: "#D4AF37", fontSize: 14, fontWeight: "600" },
  title: { fontSize: 26, fontWeight: "800", color: "#FFF", marginBottom: 12 },
  chipRow: { flexDirection: "row", gap: 8 },
  chip: {
    backgroundColor: "rgba(212,175,55,0.1)",
    paddingVertical: 5,
    paddingHorizontal: 12,
    borderRadius: 16,
  },
  chipText: { color: "#D4AF37", fontSize: 12, fontWeight: "600" },
  stepContainer: { marginTop: 24 },
  stepHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 14,
    gap: 10,
  },
  stepNumber: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#D4AF37",
    alignItems: "center",
    justifyContent: "center",
  },
  stepNumberText: { color: "#0A0A0A", fontSize: 14, fontWeight: "800" },
  stepTitle: { color: "#FFF", fontSize: 18, fontWeight: "700" },
  calendarContainer: {
    borderRadius: 16,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#1E1E1E",
  },
  horizontalScroll: { flexDirection: "row" },
  barberCard: {
    alignItems: "center",
    padding: 14,
    borderRadius: 14,
    marginRight: 12,
    backgroundColor: "#141414",
    borderWidth: 1,
    borderColor: "#1E1E1E",
    minWidth: 90,
    cursor: "pointer" as any,
  },
  barberCardSelected: { borderColor: "#D4AF37", backgroundColor: "#141208" },
  barberAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "rgba(255,255,255,0.05)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  barberAvatarSelected: { backgroundColor: "rgba(212,175,55,0.15)" },
  barberAvatarText: { fontSize: 22 },
  barberName: { color: "#AAA", fontSize: 14, fontWeight: "600" },
  barberNameSelected: { color: "#D4AF37" },
  timeGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  timeBtn: {
    backgroundColor: "#141414",
    paddingVertical: 14,
    paddingHorizontal: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#1E1E1E",
    width: "30%",
    alignItems: "center",
    cursor: "pointer" as any,
  },
  timeBtnSelected: { borderColor: "#D4AF37", backgroundColor: "#141208" },
  timeText: { color: "#AAA", fontSize: 15, fontWeight: "600" },
  timeTextSelected: { color: "#D4AF37" },
  emptyText: {
    color: "#444",
    fontSize: 14,
    textAlign: "center",
    marginVertical: 20,
  },
  chiamataBox: {
    alignItems: "center",
    backgroundColor: "rgba(212,175,55,0.05)",
    borderRadius: 16,
    padding: 24,
    borderWidth: 1,
    borderColor: "rgba(212,175,55,0.15)",
  },
  chiamataTitle: {
    color: "#D4AF37",
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 8,
  },
  chiamataText: {
    color: "#888",
    fontSize: 14,
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 16,
  },
  chiamataNumero: {
    backgroundColor: "rgba(212,175,55,0.1)",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 12,
  },
  chiamataNumeroText: { color: "#D4AF37", fontSize: 16, fontWeight: "700" },
  chiamataSede: { color: "#666", fontSize: 13, marginTop: 10 },
  riepilogo: {
    backgroundColor: "#141414",
    borderRadius: 18,
    padding: 22,
    marginTop: 28,
    borderWidth: 1,
    borderColor: "rgba(212,175,55,0.3)",
  },
  riepilogoTitle: {
    color: "#D4AF37",
    fontSize: 20,
    fontWeight: "800",
    marginBottom: 18,
    textAlign: "center",
  },
  riepilogoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#1E1E1E",
  },
  riepilogoLabel: { color: "#666", fontSize: 14 },
  riepilogoValue: { color: "#FFF", fontSize: 14, fontWeight: "600" },
  confirmBtn: {
    backgroundColor: "#D4AF37",
    padding: 18,
    borderRadius: 14,
    alignItems: "center",
    marginTop: 16,
    cursor: "pointer" as any,
  },
  confirmBtnDisabled: { opacity: 0.6 },
  confirmBtnText: { color: "#0A0A0A", fontSize: 18, fontWeight: "800" },
});
