import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#0A0A0A", padding: 24 },
  header: { marginTop: 20, marginBottom: 30 },
  backButton: { marginBottom: 20, cursor: "pointer" as any },
  backButtonText: { color: "#D4AF37", fontSize: 14, fontWeight: "600" },
  title: { fontSize: 28, fontWeight: "800", color: "#FFF", marginBottom: 10 },
  sedeChip: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(212, 175, 55, 0.1)",
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 20,
  },
  sedeChipText: { color: "#D4AF37", fontSize: 13, fontWeight: "600" },
  loadingContainer: { flex: 1, justifyContent: "center", alignItems: "center" },
  loadingText: { color: "#555", marginTop: 15, fontSize: 14 },
  cardsContainer: { gap: 12 },
  serviceCard: {
    backgroundColor: "#141414",
    padding: 18,
    borderRadius: 16,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#1E1E1E",
    ...(Platform.OS === "web" ? { cursor: "pointer" } : {}),
  },
  serviceCardPressed: {
    borderColor: "#D4AF37",
    backgroundColor: "#1A1A0A",
    transform: [{ scale: 0.98 }],
  },
  serviceIconContainer: {
    width: 56,
    height: 56,
    borderRadius: 16,
    backgroundColor: "rgba(212, 175, 55, 0.08)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 16,
  },
  serviceIcon: { fontSize: 26 },
  serviceInfo: { flex: 1 },
  serviceName: {
    color: "#FFF",
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 4,
  },
  serviceDesc: { color: "#555", fontSize: 12, marginBottom: 6, lineHeight: 16 },
  serviceMeta: { flexDirection: "row", alignItems: "center" },
  serviceDuration: { color: "#444", fontSize: 12 },
  servicePriceContainer: { flexDirection: "row", alignItems: "flex-start" },
  servicePriceSymbol: {
    color: "#D4AF37",
    fontSize: 14,
    fontWeight: "600",
    marginTop: 2,
    marginRight: 1,
  },
  servicePrice: { color: "#D4AF37", fontSize: 28, fontWeight: "800" },
});
