import { StyleSheet } from "react-native";

export const st = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#0A0A0A", padding: 24 },
  header: { marginTop: 20, marginBottom: 24 },
  backBtn: { marginBottom: 20, cursor: "pointer" as any },
  backText: { color: "#D4AF37", fontSize: 14, fontWeight: "600" },
  title: { fontSize: 28, fontWeight: "800", color: "#FFF", marginBottom: 6 },
  subtitle: { fontSize: 15, color: "#555" },
  sediList: { gap: 16 },
  sedeCard: {
    backgroundColor: "#141414",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#1E1E1E",
    overflow: "hidden",
  },
  sedeHeader: {
    flexDirection: "row",
    alignItems: "center",
    padding: 18,
    cursor: "pointer" as any,
  },
  sedeIconBox: {
    width: 52,
    height: 52,
    borderRadius: 14,
    backgroundColor: "rgba(212,175,55,0.08)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  sedeName: {
    color: "#D4AF37",
    fontSize: 20,
    fontWeight: "800",
    marginBottom: 2,
  },
  sedeAddr: { color: "#666", fontSize: 13 },
  sedeChevron: { color: "#D4AF37", fontSize: 14 },
  sedeDetails: { paddingHorizontal: 18, paddingBottom: 18 },
  divider: { height: 1, backgroundColor: "#1E1E1E", marginVertical: 14 },
  detailRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 14,
    marginBottom: 16,
  },
  detailIcon: { fontSize: 20, marginTop: 2 },
  detailLabel: {
    color: "#888",
    fontSize: 12,
    fontWeight: "600",
    marginBottom: 4,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  detailValue: { color: "#FFF", fontSize: 15, fontWeight: "600" },
  detailClosed: { color: "#F44336", fontSize: 14, marginTop: 2 },
  barbieriTitle: {
    color: "#FFF",
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 12,
  },
  barbieriGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  barbiereChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(212,175,55,0.06)",
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: "#1E1E1E",
    gap: 10,
  },
  barbiereAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(212,175,55,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  barbiereName: { color: "#FFF", fontSize: 14, fontWeight: "600" },
});
